### ISSUE TITLE
Freezes when no changes are made

### ISSUE THREAD

**Issue by rwyc-devon** [laurent22/massren#26] opened 2015-12-04 19:12 UTC
If I run massren with no parameters, and save and exit my editor without making any changes, massren hangs indefinitely. Expected behavior is for it to quit.
Tested on Arch Linux 32-Bit.
EDIT: It still does respond to SIGINT

**Comment by hashhar** [comment] 2015-12-04 19:35
I can confirm this behaviour on all platforms. I am currently busy with my exams so maybe @laurent22 would like to look into this.

**Comment by laurent22** [comment] 2015-12-04 22:51
Is it possible that, since there is not changes, the text editor is not changing the file timestamp, and so massren is not detecting the (lack of) changes? @rwyc-devon, which text editor are you using?

**Comment by hashhar** [comment] 2015-12-04 23:08
@rwyc-devon Try saving the file after some time has elapsed. That way we can isolate the cause.

**Comment by rwyc-devon** [comment] 2015-12-05 00:15
I am using vim. If I save it quits right away. So my initial description is incorrect; to reporoduce the bug you have to _not_ save, and exit.

**Comment by hashhar** [comment] 2015-12-05 00:33
Thanks for the information.

**Comment by laurent22** [comment] 2015-12-06 09:34
Ok I see, it's not really a freeze since the application is simply waiting for the file to change. Currently we don't check if the text editor has been closed without saving the file, because it's not possible to do so with GUI editors like Sublime Text.

For modal editors like Vim maybe it would make sense to have a special case. We could watch the process ID and, if it's gone, automatically exit massren. I'm closing this issue and will add a feature request for this.

**Closed by laurent22** 2015-12-06 09:34 UTC
Labels: bug
